# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "User::App"

# The default layout to use for your application (located in
# views/layouts/main.tt)
#layout: "meet"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "mason"
layout: "main.mason"
#template: "template_toolkit"

# template: "template_toolkit"
# engines:
#   template_toolkit:
#     start_tag: '[%'
#     end_tag:   '%]'
session: "YAML"

logger: 'file'
log: 'debug'

plugins:
               Database:
                   driver: 'mysql'
                   database: 'dance_with_me'
                   host: 'localhost'
                   port: 3306
                   username: 'root'
                   password: 'toor'
                   connection_check_threshold: 10
                   dbi_params:
                       RaiseError: 1
                       AutoCommit: 1
                   on_connect_do: ["SET NAMES 'utf8'", "SET CHARACTER SET 'utf8'" ]
                   log_queries: 1

